### ISSUE TITLE
Release 1.0 stable version for Go/Rust/Python

### ISSUE THREAD

**Issue by ringsaturn** [ringsaturn/tzf#102]
## 1.0.0 check lists

- [x] tzf-rel add more meta data #110 
    - [x] Release Go https://github.com/ringsaturn/tzf/releases/tag/v0.13.0
    - [x] Release Rust https://github.com/ringsaturn/tzf-rs/releases/tag/v0.4.0
    - [x] Release Python https://github.com/ringsaturn/tzfpy/releases/tag/v0.15.0
- [x] Clean up before 1.0.0 https://github.com/ringsaturn/tzf/releases
  - [x] Mark funcs as deprecated and remove before 1.0 release. Since breaking changes from upstream, like new timezone name will cause tzf init failed. tzf will only return string name, as tzf-rs&tzfpy. Refer #103 
      - [x] GetTimezoneLoc
      - [x] GetTimezone
      - [x] GetTimezoneShapeByName
      - [x] GetTimezoneShapeByShift
      - [x] https://github.com/ringsaturn/tzf/pull/111
  - [x] Move to internal
      - [x] `GetMinMax` #104 
  - [x] Return interface for finder, instead of pointer of structs. Refer #109 
- [x] #30
- [ ] ~~https://github.com/ringsaturn/geometry-rs/issues/3~~
- [ ] ~~https://github.com/ringsaturn/geometry-rs/issues/6~~
- [x] Use buf to gen go codes #181 
- [x] Release v1.0.0 for Go https://github.com/ringsaturn/tzf/releases/tag/v1.0.0
- [x] Release v1.0.0 for Rust https://github.com/ringsaturn/tzf-rs/releases/tag/v1.0.0
- [x] Release v1.0.0 for Python https://github.com/ringsaturn/tzfpy/releases/tag/v1.0.0
- [x] Release v1.0.0 for Wasm https://github.com/ringsaturn/tzf-wasm/releases/tag/v1.0.0
- [x] Release v1.0.0 for Swift https://github.com/ringsaturn/tzf-swift/releases/tag/v1.0.0

**Comment by ringsaturn** [comment]
I expect to come back to this project and release v1.0.0 before tzf’s first birthday.

**Comment by ringsaturn** [comment]
- https://github.com/ringsaturn/tzf/releases/tag/v1.0.0
- https://github.com/ringsaturn/tzf-rs/releases/tag/v1.0.0
- https://github.com/ringsaturn/tzf-wasm/releases/tag/v1.0.0
- https://github.com/ringsaturn/tzf-swift/releases/tag/v1.0.0
